export const SHOW_LOGIN_MODAL = 'MODAL/SHOW LOGIN MODAL'
export const HIDE_LOGIN_MODAL = 'MODAL/HIDE LOGIN MODAL'
export const SHOW_REGISTR_MODAL = 'MODAL/SHOW REGISTER MODAL'
export const HIDE_REGISTR_MODAL = 'MODAL/HIDE REGISTER MODAL'