export const GET_PLACES = 'PLACES/GET PLACES'
export const SET_CHOISE_PLACES = 'PLACES/SET CHOISE PLACES '
export const SET_PLACES = 'PLACES/SET PLACES '
export const GET_PLACES_FAILURE = 'PLACES/GET PLACES FAILURE'