export const GET_SESSION_BY_ID_FILM = 'SESSIONS/GET SESSION BY ID FILM'
export const GET_SESSION_FAILURE = 'SESSIONS/GET SESSIONS FAILURE'
export const GET_SESSION_HALL_ID = 'SESSIONS/GET SESSION HALL ID'